deploy:
  type: git
  repo: https://github.com/Hex2Chaos/hex2chaos.github.io
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages

theme: next
language: zh-CN
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-miku
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
